#!/usr/bin/env bash

get_file_name() {
        read -p "Enter an Apache log  file_name: " -r FILENAME
        if [ -n "$FILENAME" ]
        then
                MYFILE="$FILENAME"
        else
                return 1
        fi
}
get_log_data() {
        read -p "Enter a log data i.e ipaddress, timestamp, httpmethod, statuscode, or responsesize: " -r LOGDATA
        if [ -n "$LOGDATA" ]
        then
                LOGDATAS="$LOGDATA"
        else
                return 1
        fi
}
get_exit_choice() {
        read -p "Do you still want to continue 1 for YES or 0 for NO? " -r CHOICE
        if [ "$CHOICE" = "1" ]
        then
                return 1
        elif [ "$CHOICE" = "0" ]
        then
                return 0
        else
                return 2
        fi
}
log_regex_automation() {
        while true
        do
                get_file_name
                file_result=$?
                get_log_data
                log_result=$?
                if [ "$file_result" -eq 0  -a "$log_result" -eq 0 ]
                then
                        ./regex.rb "$MYFILE" "$LOGDATAS"
                else
                        ./regex.rb
                fi
                get_exit_choice
                exit_result=$?
                if [ "$exit_result" -eq 1 ]
                then
                        true
                elif [ "$exit_result" -eq 0 ]
                then
			echo "Exiting Logregexshell..."
			sleep 3
                        exit
                else
                        echo "Your choice of exit was $exit_result, so app is still exiting..."
                        sleep 3
                        exit
                fi
        done
}
log_regex_automation
